import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ParticlesComponent from "@/components/Particles";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JavaScript Junction",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <ParticlesComponent />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
